### ISSUE TITLE
Include set name/symbol in the IPG/MTR raw documents

### ISSUE THREAD

**Issue by KingSupernova31** [lunakv/academyruins-api#52]
They're already there for the CR; would be nice on the others.

**Comment by lunakv** [comment]
First, I'm not sure this mapping really makes sense. In my experience, the MTR updates pretty much whenever and isn't tied to set releases like the CR is. Yes, there tends to be updates to legality corresponding to new sets, but there are also other updates all over, meaning a release might have several updates. 

Second, does this serve anything besides a developer manually browsing those files? That's not a deal-breaker, mind you, I'm just trying to assess the scope of the issue. And what is the benefit for that developer? Do people associate MTR updates with specific sets? (Genuine question, I don't.)

Thirdly, putting aside backfilling the whole library, the premise isn't even true for newly-created CR files, so something would have to be built from the ground up.

**Comment by KingSupernova31** [comment]
In recent years the IPG and MTR usually update with new sets. See for example Toby Elliott's blog, which updated on each new set and talked about the updates for that set.

There have been updates that weren't correlated with any set, but that's also true for the CR, (e.g. " Companion Change"), so I don't see why the IPG/MTR poses a new problem in this respect.

A simple option to avoid having to label them by hand would be to use set symbols/names for the ones that were released along with a set, and use dates for the others.

The benefit for me is mostly with regards to the IPG; When I want to know why a change was made, I have to go find it on AR, then look up what Magic set came out on that date, then find the appropriate article on Toby's blog and/or check cards from the set to see what prompted the change. (Sometimes I do the opposite as well, wanting to see what changes were made in a specific set.) AR listing the sets directly would cut out the middle step.

I'm not sure why you mentioned "developers"; I don't think I've ever used the archives in my role as a developer, I only need new rules programmatically. I use the archives in my role as a judge who wants to understand policy history and philosophy.

This does make me curious; do you have stats on how many people use each part of the site? I'd be curious to know how many are using the archives vs. the diffs vs. the API etc.

**Comment by lunakv** [comment]
> I'm not sure why you mentioned "developers"

I assumed that since you were talking about names of raw documents, you meant the actual PDF files, whose names aren't really exposed anywhere to users directly. I see that that's not what you meant.

> A simple option to avoid having to label them by hand would be to use set symbols/names for the ones that were released along with a set, and use dates for the others.

I'm really not a fan of using a completely different kind of identifier for different documents of the same type purely based on whether they coincided with a set release or not. That seems like the kind of inconsistency that would cause a massive headache for users. 

> I just noticed that the API allows old CR downloads identified by set code, and doesn't explain how to access the companion change given that it doesn't have a set.

Those two pathological cases (companion change and cascade change) have the synthetic set codes "KHM_2" and "IKO_2" respectively. That might be good to document somewhere (though you can figure that out by accessing them through the UI).

> The benefit for me is mostly with regards to the IPG; [...]

I feel like the actual solution to your problem here isn't anything to do with mapping IPG updates to set codes, but rather including links to policy update articles with document diffs. (as discussed in lunakv/academyruins#11). That would eliminate all of the steps.

> This does make me curious; do you have stats on how many people use each part of the site? I'd be curious to know how many are using the archives vs. the diffs vs. the API etc.

Not at hand. I think I have the necessary information somewhere in the logs, so it could be dug out if I wanted to, but my monitoring system doesn't currently collect those metrics at a per-URL granularity (though that's something I've thought about changing).

**Comment by KingSupernova31** [comment]
Ah yeah, good point; I agree that implementing #11 would largely solve this problem. (Especially if the article links themselves mention the set name.)

**Comment by KingSupernova31** [comment]
Oh whoops, I've realized I opened this ticket on the wrong repo, which explains the confusion. Apologies.

https://github.com/lunakv/academyruins/issues/24
